version: "3"

services:
  node:
    build: ./api
    ports: 
      - 3000:3000
    depends_on: 
      - db
    networks: 
      - 'se'
    command: sh -c "./wait-for db:3306 -- yarn migrate && yarn start"
    environment: 
      SECRET_KEY: "1asd23SDFI8lk"
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_USERNAME: koung
      DB_PASSWORD: P@ssw0rd
      DB_DATABASE: attendant
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment: 
      MYSQL_USER: koung
      MYSQL_DATABASE: attendant
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_PORT: 3306
    networks:
      - 'se'
  web:
   build: ./frontend
   ports:
     - 80:80
   depends_on:
     - node
   networks:
     - 'se'
networks: 
  se:
